# .github/workflows/automerge-on-open.yml
name: Enable Auto‑Merge on PRs

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write
  contents: write

jobs:
  enable-automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Enable Pull Request Auto‑merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.PAT }}
          pull-request-number: ${{ github.event.pull_request.number }}  
          merge-method: merge