# .github/workflows/maven-compile.yml
name: Maven Compile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      # 1. 签出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 安装 JDK (示例用 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3. 缓存 Maven 本地仓库，加速依赖下载
      - name: Cache Maven Repo
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # 4. 只做编译
      - name: Maven clean compile
        run: mvn --batch-mode clean compile
