# .github/workflows/maven-compile.yml
name: Maven Compile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    name: Compile Java Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '24'

      - name: Cache Maven repo
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('se_app/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Maven clean compile
        working-directory: se_app
        run: mvn --batch-mode clean compile