# File: .github/workflows/pr-title-check.yml
name: PR Title Lint

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-title:
    name: Check PR Title Format
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: actions/github-script@v7
        with:
          script: |
            // Grab the PR title
            const prTitle = context.payload.pull_request.title;
            
            // Regex enforces:
            // 1) type is one of feat|fix|chore|docs|refactor|test
            // 2) followed by ": "
            // 3) summary starts with an uppercase letter
            const valid = /^(feat|fix|chore|docs|refactor|test):\s[A-Z].+/.test(prTitle);
            
            if (!valid) {
              core.setFailed(
                `PR title "${prTitle}" is invalid.\n` +
                `Titles must follow "<type>: Summary" where <type> is one of feat|fix|chore|docs|refactor|test ` +
                `and "Summary" must start with an uppercase letter.`
              );
            } else {
              console.log("PR title format is valid.");
            }
